// This file is automatically generated. Do not modify it manually.
// This file is used to store the Firebase configuration.
// It is used by the Firebase provider to initialize the Firebase app.

export const firebaseConfig = {
  apiKey: "AIzaSyCSymPvXpmGzKf6QN3TElnwxUJrxpn_RAc",
  authDomain: "studio-6611125951-c9751.firebaseapp.com",
  projectId: "studio-6611125951-c9751",
  storageBucket: "studio-6611125951-c9751.appspot.com",
  messagingSenderId: "410436937582",
  appId: "1:410436937582:web:c7decf391fe93b2f7bc37f",
};
